### ISSUE TITLE
Tilemap collision boundaries not moved when moving tilemap

### ISSUE THREAD

**Issue by Ribosom** [excaliburjs/Excalibur#3494]
### Steps to Reproduce

1. Create a Tilemap
2. Set a cell to solid
3. Move the pos of the Tilemap

Same problem appears, in other order

1. Create a Tilemap
2. Move the pos of the Tilemap
3. Set a cell to solid

only when setting the pos directly on construction it doesn't fail.

### Expected Result

Collision boundaries are moved also, when Tilemap (and its graphics) are moved.

### Actual Result

Collision boundaries are not moved.

### Environment

- Browser: Firefox 141.0
- Excalibur versions: 0.30.3
- Operating system: Windows

### Additional information

This problem also occurs when using `useLevelOffsets: false` with the LDtk plugin and having World Coordinates != 0,0 - as a direct result of this bug (because in the plugin the pos is changed after construction).

### Minimal code

```ts
game.start('start', {
  loader,
}).then(() => {

  const spriteSheet = SpriteSheet.fromImageSource({
    image: Resources.TileMap,
    grid: {
      rows: 4,
      columns: 4,
      spriteHeight: 32,
      spriteWidth: 32
    },
    spacing: {
      margin: {
        x: 0,
        y: 0
      }
    }
  });

  const tilemap = new TileMap({
    rows: 4,
    columns: 4,
    tileWidth: 32,
    tileHeight: 32,
  });
  let tile1 = tilemap.getTile(0, 0);
  if (tile1) {
    tile1.solid = true // XXX first relevant line
  }

  for (let tile of tilemap.tiles) {
    const sprite = spriteSheet.getSprite(0, 0);
    if (sprite) {
      tile.addGraphic(sprite);
    }
  }

  tilemap.pos = tilemap.pos.add(vec(512, 0)) // XXX second relevant line

  game.currentScene.add(tilemap)
});
```

**Comment by eonarheim** [comment]
@Ribosom Thanks for the bug!

**Comment by eonarheim** [comment]
Doing a bit of research I think I fixed this one here https://github.com/excaliburjs/Excalibur/commit/4ffa2fa9da992a7a2aa4082e77706dff4b350252 

Latest main should work `npm install excalibur@next` in theory

**Comment by Ribosom** [comment]
Ok I tried it after executing `npm install excalibur@next` again, and sadly it still does not work.

weird... the code looks like it should have fixed this.

edit: if I "debugged" correctly, colliders are set dirty and afterwards updateColliders is called correctly, but maybe that method has an bug?

**Comment by eonarheim** [comment]
I'll look into this closer
